import os


# Web application settings
PRODUCTION_MODE = os.getenv('ENV_PRODUCTION_MODE') == 'True'
APPLICATION_SECRET = os.getenv('ENV_APPLICATION_SECRET')
APPLICATION_URL = os.getenv('ENV_APPLICATION_URL')
PROTOCOL_SECRET = os.getenv('ENV_PROTOCOL_SECRET')

# Deep learning classifier settings
RESIZE_RATIO = (64, 64, 3)
CROP_OFFSET = 15
USE_CROP = False
BORDER_THICKNESS = 3
DETECTOR_KERNEL_FILE_PATH = os.getenv('ENV_DETECTOR_KERNEL_FILE_PATH')
SCANNER_KERNEL_FILE_PATH = os.getenv('ENV_SCANNER_KERNEL_FILE_PATH')
